### ISSUE TITLE
Crashes on kotlinx.coroutines upgrade

### ISSUE THREAD

**Issue by jakoss** [cashapp/turbine#29]
After upgrading coroutines package to 1.4.3 i'm getting crashes while using `.test`.
```
NoSuchMethodError: kotlinx.coroutines.TimeoutKt.withTimeout
```

This is basically caused by experimental api usage while using kotlin in lower version then the coroutines library. So when `kotlinx.coroutines` upgraded to kotlin 1.4.30 all experimental inline-classes API are not compatibile with any library that relies on them. Details: https://github.com/Kotlin/kotlinx.coroutines/issues/2565

Can you release new version with bumped `kotlinx.coroutines` version asap?

**Comment by Egorand** [comment]
Please use the latest snapshot until the update is released

**Comment by qwexter** [comment]
If you want use it on jvm(android) try 
`app.cash.turbine:turbine-jvm:0.5.0-SNAPSHOT`

**Comment by JakeWharton** [comment]
I'm back to work next week. I'll make a release Monday, assuming the seemingly-now-broken CI build isn't a blocker...

**Comment by JakeWharton** [comment]
0.4.1 released
