### ISSUE TITLE
Flow tests do not work on Kotlin 1.4.10 JVM

### ISSUE THREAD

**Issue by edgar-zigis** [cashapp/turbine#21]
Hello, I am trying to use this library in our Android app using Kotlin 1.4.10, unfortunately even when trying to perform a basic sample test like this one
```
flowOf("one", "two").test {
  assertEquals("one", expectItem())
  assertEquals("two", expectItem())
  expectComplete()
}
```
I get an exception:
`java.lang.NoSuchMethodError: kotlinx.coroutines.channels.ChannelKt.Channel$default(ILkotlinx/coroutines/channels/BufferOverflow;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/coroutines/channels/Channel;`

I use **InstantTaskExecutorRule** and blocking **CoroutineRule** to mock things.

**Comment by Egorand** [comment]
A sample project that reproduces the issue would be very helpful, otherwise this doesn't seem to be actionable - we've got similar tests in our code and they pass.

**Comment by edgar-zigis** [comment]
Ok, I will try to assemble one today or tomorrow.

**Comment by JakeWharton** [comment]
Usually this means you're using an old version of kotlinx.coroutines. Or too-new, perhaps.

**Comment by edgar-zigis** [comment]
You are right @JakeWharton , I was silly enough to use this on coroutines **1.3.8**. Thank you!
