### ISSUE TITLE
Updating to 0.5.2 cause :shared:linkDebugTestIosX64 fail

### ISSUE THREAD

**Issue by fabiosanto** [cashapp/turbine#49]
Hey everyone, I wanted to share this issue I ran into since updating turbine to 0.5.2 from 0.4.1.
I'm on a Kotlin Multiplatform Project and using turbine to unit test on `commonTest`, `androidTest` and `iosTest` source sets.
In order to get this https://github.com/cashapp/turbine/pull/46 fix I updated to 0.5.2.
This release now supports kotlin native builds but it seems to introduce the following issue when building ios tests:
```
e: Compilation failed: Deserializer for declaration public kotlinx.coroutines.channels/ValueOrClosed|null[0] is not found
 * Source files: 
 * Compiler version info: Konan: 1.5.10 / Kotlin: 1.5.10
 * Output kind: STATIC_CACHE
e: java.lang.IllegalStateException: Deserializer for declaration public kotlinx.coroutines.channels/ValueOrClosed|null[0] is not found
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.handleNoModuleDeserializerFound(KotlinIrLinker.kt:473)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.findModuleDeserializer(KotlinIrLinker.kt:361)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeIrSymbolData(KotlinIrLinker.kt:390)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeIrSymbol(KotlinIrLinker.kt:406)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrSymbolAndRemap(IrFileDeserializer.kt:145)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeSimpleType(IrFileDeserializer.kt:170)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrTypeData(IrFileDeserializer.kt:214)
	at ....
```

As per this https://youtrack.jetbrains.com/issue/KT-41378 It seems being related to coroutines dependency being overridden. 
I see Turbine depends on 1.5.0 coroutine and not on 1.5.0-native-mt so on my side I did provide the `strictly("1.5.0-native-mt")` clause but still no improvements.

Do you see any reason why It won't override Turbine's dependency?

**Comment by JakeWharton** [comment]
I have also seen this myself (not with Turbine though), and I don't remember how I fixed it. It's definitely a build configuration problem of some sort.

**Comment by micHar** [comment]
EDIT: Okay, my issue is probably not linked to turbine.


Original issue:

I also use `strictly 1.5.0-native-mt` and also have this problem. Have been using `0.5.2` without issues for some time but after a few lib updates (maybe it was kotlin to 1.5.10?) it got messed up in similar way.

I just updated to `0.6.0` and have something else but still from the same family of issues, I suppose.

I'm on m1 mac. The ios code builds fine, only ios tests are messed.

On both the liberica bellsoft jdk (aarch64, I think) and embedded (x86_64?):
```
e: Compilation failed: Could not initialize class llvm.llvm
 * Source files: 
 * Compiler version info: Konan: 1.5.10 / Kotlin: 1.5.10
 * Output kind: STATIC_CACHE
e: java.lang.NoClassDefFoundError: Could not initialize class llvm.llvm
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$contextLLVMSetupPhase$1.invoke(BitcodePhases.kt:34)
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$contextLLVMSetupPhase$1.invoke(BitcodePhases.kt:28)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:63)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:61)
```

Did you fix it @fabiosanto?

**Comment by JakeWharton** [comment]
Going to close. I also don't think this is a Turbine-specific issue but it could be something that Turbine might inadvertently cause due to a change in a transitive dependency version.

If someone can create a reliably reproducing project I can try to take a look but otherwise I don't see any action to take.
